# Generated by Django 4.2.1 on 2023-06-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_bookinstance_borrower_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='2536535200223', help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>*Si no se proporciona un ISBN, se generará uno aleatoriamente de 13 dígitos.*', max_length=13, unique=True, verbose_name='ISBN'),
        ),
    ]
